import * as T from '../vendor/three.module.js';
export class PhysicsDebug {
 constructor(root,items,scene){this.bones=new T.SkeletonHelper(root);this.bones.visible=false;scene.add(this.bones);this.items=items.filter(s=>s.bone.children.some(c=>c.isBone));this.points=new Float32Array(this.items.length*6);this.geometry=new T.BufferGeometry();this.geometry.setAttribute('position',new T.BufferAttribute(this.points,3));this.material=new T.LineBasicMaterial({color:0xffa030,depthTest:false});this.chains=new T.LineSegments(this.geometry,this.material);this.chains.frustumCulled=false;this.chains.visible=false;scene.add(this.chains);this.a=new T.Vector3();this.b=new T.Vector3();}
 update(){if(!this.chains.visible)return;let i=0;for(const s of this.items){s.bone.getWorldPosition(this.a);s.bone.children.find(c=>c.isBone).getWorldPosition(this.b);this.a.toArray(this.points,i);this.b.toArray(this.points,i+3);i+=6}this.geometry.attributes.position.needsUpdate=true;}
 dispose(){this.bones.removeFromParent();this.bones.dispose();this.chains.removeFromParent();this.geometry.dispose();this.material.dispose();}
}
export class ChainContacts {
 constructor(secondary,rig){this.enabled=true;this.items=secondary.items.filter(s=>s.bone.children.some(c=>c.isBone));this.rig=rig;this.contacts=0;this.origin=new T.Vector3();this.tip=new T.Vector3();this.target=new T.Vector3();this.from=new T.Vector3();this.to=new T.Vector3();this.q=new T.Quaternion();this.parent=new T.Quaternion();this.identity=new T.Quaternion();this.temp=new T.Quaternion();}
 update(){this.contacts=0;if(!this.enabled)return;for(const s of this.items){const bone=s.bone,child=bone.children.find(c=>c.isBone);bone.getWorldPosition(this.origin);child.getWorldPosition(this.tip);this.target.copy(this.tip);const hair=bone.name.includes('Hair');for(const c of this.rig.items){if(!(hair?['Head','Chest','UpperArm_L','UpperArm_R'].includes(c.name):c.name.startsWith('Thigh')))continue;if(c.project(this.target,s.profile?.collisionRadius||.008))this.contacts++}if(this.target.distanceToSquared(this.tip)<1e-10)continue;this.from.subVectors(this.tip,this.origin).normalize();this.to.subVectors(this.target,this.origin).normalize();this.q.setFromUnitVectors(this.from,this.to);const angle=this.identity.angleTo(this.q),limit=Math.min(.10,s.profile?.maxAngle||.05);if(angle>limit)this.q.slerpQuaternions(this.identity,this.temp.copy(this.q),limit/angle);bone.parent.getWorldQuaternion(this.parent);this.q.premultiply(this.temp.copy(this.parent).invert()).multiply(this.parent);bone.quaternion.premultiply(this.q);bone.updateWorldMatrix(false,true);}}
}
